#ifndef CONSTANTS_H
#define CONSTANTS_H

#define TIME_UNIT 250 // ~319
#define TIME_UNIT_TOLERANCE TIME_UNIT / 2 // 319 - 250 = 69
#define START_BIT_DURATION TIME_UNIT * 10 // 2641
#define START_BIT_TOLERANCE TIME_UNIT
#define STOP_BIT_DURATION 9000
#define MESSAGE_BUFFER_LENGTH 32
#define RECEIVE_BUFFER_LENGTH MESSAGE_BUFFER_LENGTH * 2

#define N_REPEAT_TRANSMISSION 5

#endif
